### ISSUE TITLE
Provisioning fails with ipv6

### ISSUE THREAD

**Issue by daviswill2** [rancher/qa-tasks#1043] opened 2023-11-14 15:44 UTC
https://github.com/rancher/rancher/issues/42411

**Comment by daviswill2** [comment] 2023-11-14 15:44
2.8.0 issue that needs to be automated.

**Comment by markusewalker** [comment] 2024-05-03 15:04
Closing as duplicate of https://github.com/rancher/qa-tasks/issues/942.

**Closed as completed by markusewalker** 2024-05-03 15:04 UTC
Labels: team/area2, area/automation-test
