### ISSUE TITLE
rancher-ha deploy job fails when hardening flag is enabled for rke1 clusters

### ISSUE THREAD

**Issue by anupama2501** [rancher/qa-tasks#965] opened 2023-10-02 19:33 UTC
There are few resources in the [hardened-cluster.yml](https://github.com/rancher/rancher/blob/release/v2.8/tests/validation/tests/v3_api/resource/hardened-cluster.yml) file, that corresponds to pod security policies.

https://github.com/rancher/rancher/blob/release/v2.8/tests/validation/tests/v3_api/resource/hardened-cluster.yml#L31 should be set to false. 
There are also other references as the following that should be removed as well. 

- https://github.com/rancher/rancher/blob/release/v2.8/tests/validation/tests/v3_api/resource/hardened-cluster.yml#L98
- https://github.com/rancher/rancher/blob/release/v2.8/tests/validation/tests/v3_api/resource/hardened-cluster.yml#L133

Reference hardening guide from rancher docs to create an rke1 standalone cluster https://ranchermanager.docs.rancher.com/v2.7/pages-for-subheaders/rke1-hardening-guide#reference-hardened-rke-cluster-template-configuration

**Comment by slickwarren** [comment] 2024-02-02 22:17
closing as duplicate of https://github.com/rancher/qa-tasks/issues/632

**Closed as completed by slickwarren** 2024-02-02 22:17 UTC
Labels: team/area2, area/automation-test
