### ISSUE TITLE
v2.6.4 Support Matrix checks - Validate RHEL 8.5 for 2.6.4 Rancher release

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#228] opened 2022-02-11 20:33 UTC
Start after Feature complete date. And Due by - 03/04/2022

On 2.6-head rancher version or on the latest 2.6.4-rc version using the default k8s version

---

### Team 2 tasks - Izaac

**HA Rancher testing**

- [x] Deploy HA with RKE1 local cluster using Private custom AMI - RHEL 8.5 with SElinux _enabled_ (Docker and OS level)
- [x] Deploy a downstream RKE1 custom cluster using Private custom AMI RHEL 8.5 with SElinux _enabled_ (Docker and OS level)
- [x] RUn v3_needs_cluster Automation on the cluster. All tests must pass.

**RKE1 Provisioning**

- [x] Deploy RKE1 custom cluster. And run regression tests on the cluster. Use a Private custom AMI - RHEL 8.5 with SElinux _disabled_
- [x] Deploy RKE1 Node Drive (AWS) cluster. And run regression tests on the cluster. Use a Public AMI RHEL 8.5 for this task

**RKE2 provisioning**
- [x] Deploy RKE2 custom cluster. And run regression tests on the cluster. Use a Private custom AMI - RHEL 8.5 with SElinux _disabled_
- [ ] Deploy RKE2 Node Drive (AWS) cluster. And run regression tests on the cluster. Use a Public AMI RHEL 8.5 for this task
  - Issue: https://github.com/rancher/rancher/issues/36731

---
### Team 3 tasks
- [x] Deploy HA with RKE1 local cluster using Private custom AMI - RHEL 8.5 with SElinux _enabled_ (Docker and OS level)
- [x] Deploy a downstream RKE1 custom cluster using Private custom AMI RHEL 8.5 with SElinux _enabled_ (Docker and OS level)
- [x] Deploy 1/v2 charts on the downstream cluster
- [x] V1 charts
- - [x] GDNS
- [x] V2 charts
- - [x] Istio
- - [x] Monitoring
    - Issue: https://github.com/rancher/rancher/issues/36742
- - [x] Alerting Drivers
- - [x] Fleet
- - [x] CIS --> On a cis 1.6 hardened scan on a hardened cluster and permissive scan on a non-hardened cluster
- - [x] Backup Restore
- - [x] Longhorn
- - [x] Logging
- - [x] GKE

**Comment by izaac** [comment] 2022-03-03 01:17
As of today (03/02/2022) testing has progress using Rancher version `v2.6.4-rc4` (down to _Deploy RKE2 custom cluster. And run regression tests on the cluster. Use a Private custom AMI - RHEL 8.5 with SElinux disabled_ is completed.)

I am having trouble with the Public RHEL 8.5 and RKE2 downstream cluster for the remaining checkbox in the Team 2 section.

I will continue with the team 3 tasks next while I get more information related to the before mentioned issue.

**Comment by izaac** [comment] 2022-03-04 16:01
Completed: 

- CIS 1.6 **hardened** scan on RHEL 8.5 SELinux OS+Docker, Rancher SELinux RPM and CIS configured (hardened nodes). 
- CIS 1.6 **permissive** scan on RHEL 8.5 SELinux OS+Docker, Rancher SELinux RPM and CIS configured. 

Screens:

<img width="1088" alt="Screen Shot 2022-03-04 at 9 00 56 AM" src="https://user-images.githubusercontent.com/27659/156797248-ffc052ed-843a-48eb-aa1c-b17f28506a9e.png">

<img width="1099" alt="Screen Shot 2022-03-04 at 9 01 15 AM" src="https://user-images.githubusercontent.com/27659/156797274-527296c3-7f97-4525-bb9e-faa94cc2ed03.png">

**Comment by izaac** [comment] 2022-03-05 02:55
Final check of GDNS was done using k8s `v1.21.9-rancher1-2` due to a known issue where the GDNS app has to be updated to support k8s 1.22
https://github.com/rancher/rancher/issues/35909#issuecomment-996365828

**Comment by izaac** [comment] 2022-03-05 02:56
Closing only issue left is linked in the description and in this comment.
https://github.com/rancher/rancher/issues/36731

**Closed as completed by izaac** 2022-03-05 02:56 UTC
Labels: team/area3, area/release-testing, qa-release-task
