### ISSUE TITLE
Add delete cluster test cases to test validations.

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#634] opened 2023-02-24 15:34 UTC
Include test cases to delete clusters for rke1,rke2,k3s custom and node provider clusters.

**Comment by markusewalker** [comment] 2023-03-31 18:19
@igomez06 if it's alright with you, I'm going to assign this to Infra-cloud team as this is a good candidate for release testing automation.

**Comment by igomez06** [comment] 2023-03-31 18:56
> @igomez06 if it's alright with you, I'm going to assign this to Infra-cloud team as this is a good candidate for release testing automation.

Sounds good to me

**Comment by mitulshah-suse** [comment] 2023-04-10 07:14
@igomez06 @markusewalker @sowmyav27 Can you please confirm if this is a duplicate of https://github.com/rancher/qa-tasks/issues/669

**Comment by markusewalker** [comment] 2023-04-10 15:06
Yeah, they look to be duplicates. I'll close this one out in favor of the other issue.

**Closed as completed by markusewalker** 2023-04-10 15:06 UTC
Labels: area/automation-framework, area/release-testing, team/infracloud
